### ISSUE TITLE
MCrypt is deprecated in PHP 7.1

### ISSUE THREAD

**Issue by ghost** [interactive32/ducksell#1]
I was running the latest version of XAMPP (PHP 7.1) to test out the script and ran into this error after installing and trying to load the website:

![error](https://cloud.githubusercontent.com/assets/12932196/24086723/3baad248-0ceb-11e7-9ec3-b2d2e47dc677.png)

So I installed XAMPP with PHP 7.0 and everything worked fine. But for now DuckSell won't work with PHP 7.1 and above. Not sure about a workaround though updating Laravel might be needed.

**Comment by alcalbg** [comment]
fixed with 45ed68643f1422bcccc4634690afcc6d0ff00501 
new tests added from 5.6 to 7.3 on Travis CI
