### ISSUE TITLE
laravel

### ISSUE THREAD

**Issue by jackttcoms** [interactive32/ducksell#3]
is it possible fro you to upload a version with laravel already in the zip file because my hosting supports laravel but not composer or phar extention

thanks

**Comment by alcalbg** [comment]
Yes, you can download compiled version with installer here http://store.interactive32.com/getproduct/11

**Comment by jackttcoms** [comment]
I did it but have not received email? thanks

**Comment by HikeAndMap** [comment]
Hi Jack, 
 
sorry what? 
 
I’m busy with the kids here everyone sick so please excuse me if I missed something.
 
But what are you referring to? 

**Comment by jackttcoms** [comment]
I got told to download this     Yes, you can download compiled version with installer here http://store.interactive32.com/getproduct/11    but the email never came to me with the download
